version: "3.8"

services:
  w4-postgres:
    image: postgres
    container_name: w4-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./database/script.sql:/docker-entrypoint-initdb.d/init.sql"
      - "w4-postgres-data:/var/lib/postgresql/data"
    networks:
      - w4-postgres-pgadmin-network

  w4-pgadmin:
    image: dpage/pgadmin4
    container_name: w4-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "lemuel.czara@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin2022"
    ports:
      - "16543:80"
    depends_on:
      - w4-postgres
    networks:
      - w4-postgres-pgadmin-network

networks:
  w4-postgres-pgadmin-network:
    driver: bridge

volumes:
  w4-postgres-data: